Terminal.MvcUI/ViewModels/TerminalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Terminal.Core.Objects;

namespace Terminal.MvcUI.ViewModels
{
    public class TerminalViewModel
    {
        public string Display { get; set; }
        public string Notifications { get; set; }
        public string Cli { get; set; }
        public string ContextText { get; set; }
        public bool PasswordField { get; set; }
        public string Title { get; set; }
        public CommandContext CommandContext { get; set; }

        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Terminal.MvcUI/Controllers/ApiController.cs
using Microsoft.Web.Mvc;
using SignalR;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Web.Mvc;
using System.Web.Security;
using Terminal.Core;
using Terminal.Core.Data;
using Terminal.Core.Enums;
using Terminal.Core.ExtensionMethods;
using Terminal.Core.Objects;
using Terminal.MvcUI.Data;

namespace Terminal.MvcUI.Controllers
{
    [ValidateInput(false)]
    public class ApiController : Controller
    {
        TerminalApi _terminalApi;
        IDataBucket _dataBucket;
        UIContext _uiContext;

        public ApiController(TerminalApi terminalApi, IDataBucket dataBucket, UIContext uiContext)
        {
            _terminalApi = terminalApi;
            _dataBucket = dataBucket;
            _uiContext = uiContext;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            var response = filterContext.HttpContext.Response;
            response.Write(filterContext.Exception.Message);
            response.ContentType = MediaTypeNames.Text.Plain;
            filterContext.ExceptionHandled = true;
        }


        public JsonResult Index([Deserialize]CommandContext commandContext, string cli, bool parseAsHtml = false)
        {
            _terminalApi.Username = User.Identity.IsAuthenticated ? User.Identity.Name : null;
            _terminalApi.IPAddress = Request.UserHostAddress;
            _terminalApi.CommandContext = commandContext;
            _terminalApi.ParseAsHtml = parseAsHtml;
            var commandResult = _terminalApi.ExecuteCommand(cli);

            if (User.Identity.IsAuthenticated)
            {
                if (commandResult.CurrentUser == null)
                    FormsAuthentication.SignOut();
            }
            else
            {
                if (commandResult.CurrentUser != null)
                    FormsAuthentication.SetAuthCookie(commandResult.CurrentUser.Username, true);
            }

            var displayItems = new List<ApiDisplayItem>();
            commandResult.DisplayItems.ForEach(x => displayItems.Add(new ApiDisplayItem
            {
                Text = x.Text,
                Bold = (x.DisplayMode & DisplayMode.Bold) != 0,
                Dim = (x.DisplayMode & DisplayMode.Dim) != 0,
                DontType = (x.DisplayMode & DisplayMode.DontType) != 0,
                Inverted = (x.DisplayMode & DisplayMode.Inverted) != 0,
                Italics = (x.DisplayMode & DisplayMode.Italics) != 0,
                Mute = (x.DisplayMode & DisplayMode.Mute) != 0,
                Parse = (x.DisplayMode & DisplayMode.Parse) != 0
            }));

            var apiResult = new ApiResult
            {
                ClearScreen = commandResult.ClearScreen,
                Command = commandResult.Command,
                ContextStatus = commandResult.CommandContext.Status.ToString(),
                ContextText = commandResult.CommandContext.Command
                + (commandResult.CommandContext.Text.IsNullOrEmpty()
                ? null : string.Format(" {0}", _terminalApi.CommandContext.Text)),
                CurrentUser = commandResult.CurrentUser != null ? commandResult.CurrentUser.Username : null,
                DisplayItems = displayItems,
                EditText = commandResult.EditText,
                Exit = commandResult.Exit,
                PasswordField = commandResult.PasswordField,
                ScrollToBottom = commandResult.ScrollToBottom,
                SessionId = Session.SessionID,
                TerminalTitle = commandResult.TerminalTitle,
                CommandContext = commandResult.CommandContext.Serialize()
            };
            //string json = new JavaScriptSerializer().Serialize(apiResult);
            //return callback != null ? string.Format("{0}({1});", callback, json) : json;
            return Json(apiResult);
        }

        public JsonResult Metadata()
        {
            var metadata = new
            {
                Command = new { Type = "string", Description = "The command that was processed by the terminal core." },
                ContextStatus = new { Type = "string", Description = "The current command context status. Disabled, Passive, or Forced" },
                ContextText = new { Type = "string", Description = "Text to be displayed next to the CLI bracket representing the current command context." },
                CurrentUser = new { Type = "string", Description = "Displays username of the logged-in user. Null if no user is logged in." },
                EditText = new { Type = "string", Description = "Text to be inserted into the CLI for the user to edit." },
                SessionId = new { Type = "string", Description = "The session ID to be submitted with each subsequent request." },
                TerminalTitle = new { Type = "string", Description = "Text to be displayed in the title bar of the client application." },
                ClearScreen = new { Type = "boolean", Description = "True if the screen should be cleared." },
                Exit = new { Type = "boolean", Description = "True if the client application should exit." },
                PasswordField = new { Type = "boolean", Description = "True if the client application should transform the command line into a password field for the next request." },
                ScrollToBottom = new { Type = "boolean", Description = "True if clients capable of controlling scrolling should scroll to the bottom." },

                DisplayItems = new List<object>()
                {
                    new
                    {
                        Dim = new { Type="boolean", Description = "True if the text should be more subtle than the standard text." },
                        Inverted = new { Type = "boolean", Description = "True if the colors for this line of text should be inverted. (i.e. Foreground Color = Background Color & Background Color = Foreground Color)" },
                        Parse = new { Type = "boolean", Description = "True if the line of text could contain BBCode tags to be parsed. This is true even if the tags have already been parsed as HTML via the parseAsHtml API option." },
                        Italics = new { Type = "boolean", Description = "True if the text should be displayed in italics." },
                        Bold = new { Type = "boolean", Description = "True if the text should be displayed in bold." },
                        DontType = new { Type = "boolean", Description = "True if the text should not be displayed by any character-by-charcater typing script. (e.g. jQuery.coolType)" },
                        Mute = new { Type = "boolean", Description = "True if sound should not be played while the text is being rendered character-by-character. (This will be true for all items if the user has specified the mute option in their settings)" },
                        Text = new { Type = "string", Description = "The text to be displayed. Usually a single line but may contain new-line characters or break tags if the parseAsHtml API option was set to true." }
                    }
                }
            };

            return Json(metadata, JsonRequestBehavior.AllowGet);
        }

        public void ConnectUser(string connectionId)
        {
            var username = User.Identity.IsAuthenticated ? User.Identity.Name : null;

            var signalRConnection = _uiContext.SignalRConnections
                .SingleOrDefault(x => x.ConnectionId == connectionId);

            if (signalRConnection == null)
            {
                signalRConnection = new SignalRConnection
                {
                    ConnectionId = connectionId,
                    SessionId = Session.SessionID,
                    Username = username
                };
                _uiContext.SignalRConnections.Add(signalRConnection);
            }
            else
                signalRConnection.Username = username;

            _uiContext.SaveChanges();
        }
    }
}

Terminal.MvcUI/Controllers/TerminalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Terminal.Core;
using Terminal.Core.Objects;
using Terminal.MvcUI.ViewModels;
using Terminal.Core.ExtensionMethods;
using System.Web.Security;
using Terminal.Core.Settings;
using System.Text;
using Terminal.Core.Enums;
using System.Net;
using System.Configuration;
using Microsoft.Web.Mvc;

namespace Terminal.MvcUI.Controllers
{
    [ValidateInput(false)]
    public class TerminalController : Controller
    {
        private TerminalApi _terminalCore;

        public TerminalController(TerminalApi terminalCore)
        {
            _terminalCore = terminalCore;
        }

        public ViewResult Index(string Cli, string Display, [Deserialize]CommandContext CommandContext)
        {
            if (User.Identity.IsAuthenticated || Session["hasAccess"] != null)
            {
                ModelState.Clear();
                _terminalCore.Username = User.Identity.IsAuthenticated ? User.Identity.Name : null;
                _terminalCore.IPAddress = Request.UserHostAddress;
                _terminalCore.CommandContext = CommandContext;
                _terminalCore.ParseAsHtml = true;
                var commandResult = _terminalCore.ExecuteCommand(Cli);

                if (commandResult.ClearScreen)
                    Display = null;

                if (User.Identity.IsAuthenticated)
                {
                    if (commandResult.CurrentUser == null)
                        FormsAuthentication.SignOut();
                }
                else
                {
                    if (commandResult.CurrentUser != null)
                        FormsAuthentication.SetAuthCookie(commandResult.CurrentUser.Username, true);
                }

                var display = new StringBuilder();
                foreach (var displayItem in commandResult.DisplayItems)
                {
                    display.Append(displayItem.Text);
                    display.Append("<br />");
                }

                if (Display != null)
                    Display += "<br />";

                var viewModel = new TerminalViewModel
                {
                    Cli = commandResult.EditText,
                    ContextText = commandResult.CommandContext.Command
                    + (commandResult.CommandContext.Text.IsNullOrEmpty()
                    ? null : string.Format(" {0}", _terminalCore.CommandContext.Text)),
                    Display = Display + display.ToString(),
                    PasswordField = commandResult.PasswordField,
                    Notifications = string.Empty,
                    Title = commandResult.TerminalTitle,
                    CommandContext = commandResult.CommandContext
                };

                return View(viewModel);
            }
            else
                return View("Facade");
        }

        public RedirectToRouteResult GetAccess(bool hasAccess = false)
        {
            Session["hasAccess"] = hasAccess;
            return RedirectToAction("Index");
        }
    }
}

Terminal.MvcUI/Views/Terminal/Facade.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Omega Orthodontics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="@Url.Content("~/content/bootstrap.css")" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 60px;
        }

        /* Custom container */
        .container {
            margin: 0 auto;
            max-width: 1000px;
        }

            .container > hr {
                margin: 60px 0;
            }

        /* Main marketing message and sign up button */
        .jumbotron {
            margin: 80px 0;
            text-align: center;
        }

            .jumbotron h1 {
                font-size: 100px;
                line-height: 1;
            }

            .jumbotron .lead {
                font-size: 24px;
                line-height: 1.25;
            }

            .jumbotron .btn {
                font-size: 21px;
                padding: 14px 24px;
            }

        /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }

            .marketing p + h4 {
                margin-top: 28px;
            }


        /* Customize the navbar links to be fill the entire space of the .navbar */
        .navbar .navbar-inner {
            padding: 0;
        }

        .navbar .nav {
            margin: 0;
            display: table;
            width: 100%;
        }

            .navbar .nav li {
                display: table-cell;
                width: 1%;
                float: none;
            }

                .navbar .nav li a {
                    font-weight: bold;
                    text-align: center;
                    border-left: 1px solid rgba(255,255,255,.75);
                    border-right: 1px solid rgba(0,0,0,.1);
                }

                .navbar .nav li:first-child a {
                    border-left: 0;
                    border-radius: 3px 0 0 3px;
                }

                .navbar .nav li:last-child a {
                    border-right: 0;
                    border-radius: 0 3px 3px 0;
                }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-2.0.0.min.js")"></script>
</head>

<body>

    <div class="container">

        <div class="masthead">
            <img style="width: 250px;" src="@Url.Content("~/content/OmegaSystemsLogo.jpg")" />
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#services">Services</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.navbar -->
        </div>
        @*<img src="@Url.Content("~/content/OrthodonticsJumbo.jpg")" />*@
        <!-- Jumbotron -->
        <div class="jumbotron" style="background-image: url('@Url.Content("~/content/OrthodonticsJumbo.jpg")'); height: 340px; position: relative; margin-bottom: 20px;">
            <a style="float: right; margin: 25px 25px 0 0;" class="btn btn-large btn-success" href="#contact">Contact Us Today</a>
            <div style="height: 200px; width: 100%; position: absolute; top: 140px; left: 0; background-color: #fff; opacity: .5;"></div>
            <div style="height: 163px; position: absolute; top: 140px; left: 0; padding: 17.5px; text-align: left;">
                <h2 style="font-size: 55px; margin-bottom: 25px;">We Design New Smiles</h2>
                <p class="lead">At Omega we don't want you to be self-conscious about your smile. We want the first thing that others notice about you to be your wonderful smile. Healthy and beautiful teeth are our specialty.</p>
            </div>
        </div>
        <!-- Example row of columns -->
        <div class="row-fluid" id="services">
            <div class="span4">
                <h2>Invisalign</h2>
                <p>We care about both appearance and comfort at Omega. Our Invisalign services are the best in the business.</p>
            </div>
            <div class="span4">
                <h2>Traditional Braces</h2>
                <p>We understand that your time and money is important to you. We offer the best traditional braces on the market.</p>
            </div>
            <div class="span4">
                <h2>General Dentistry</h2>
                <p>We also offer a wide array of other services. To learn more simply contact us and one of our technitians will be happy to answer any questions!</p>
            </div>
        </div>

        <hr />

        <div style="margin: auto; width: 350px; border: solid 1px #aaa; border-radius: 10px; box-shadow: 10px 10px 5px #888888; padding: 15px;" id="contact">
            <h3 style="text-align: center;">Request an Appointment</h3>
            <form method="post" action="@Url.Action("GetAccess")">
                Name <input id="name" type="text" /><br />
                <img id="resistance" style="display: none; margin-bottom: 15px;" src="@Url.Content("~/content/resistance.jpg")" />
                <div id="junk">
                    Phone <input id="phone" type="text" /><br />
                    Email <input id="email" type="text" /><br />
                    <br />
                    Questions/Concerns<br />
                    <textarea id="questions" style="width: 300px; height: 100px;"></textarea>
                    <br />
                </div>
                <input type="hidden" name="hasAccess" value="true" />
                <input id="submitRequest" class="btn btn-success" type="submit" value="Submit" /> <span id="result" style="color: #090; font-weight: bold; display: none;">Success! We will contact you soon.</span>
            </form>
            <script type="text/javascript">
                $(function () {
                    $('#submitRequest').click(function (e) {
                        if (!$(this).hasClass('btn-info')) {
                            e.preventDefault();
                            $('#name').val('');
                            $('#phone').val('');
                            $('#email').val('');
                            $('#questions').val('');
                            $('#result').fadeIn(function () {
                                setTimeout(function () {
                                    $('#result').fadeOut();
                                }, 3000);
                            });
                        }
                    });
                    $('#name').keyup(function (e) {
                        if ($(this).val().toUpperCase() === 'RESIST THE INGRESS') {
                            $('#submitRequest').removeClass('btn-success').addClass('btn-info');
                            $('#junk').slideUp();
                            $('#resistance').slideDown();
                        }
                        else {
                            $('#submitRequest').removeClass('btn-info').addClass('btn-success');
                            $('#junk').slideDown();
                            $('#resistance').slideUp();
                        }
                    });
                });
            </script>
        </div>

        <hr />

        <div class="footer">
            <p>&copy; Omega 2013</p>
        </div>

    </div>
    <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

</body>
</html>

Terminal.MvcUI/Views/Terminal/Index.cshtml
@model Terminal.MvcUI.ViewModels.TerminalViewModel
@using Terminal.Core.Utilities;
@using Terminal.Core.Enums;
@using System.Configuration;
@{
    ViewBag.Title = Model.Title;
}
<script type="text/javascript">
    var rootPath = '@Url.Content("~")',
        username = '@User.Identity.Name';

    soundManager.url = rootPath + 'Content/SoundManager2/';
    //soundManager.useHTML5Audio = true;
    soundManager.allowScriptAccess = 'always';
    $(function () {
        @if (DateTime.Now.Month == (int)Month.October)
        {
            <text>
                soundManager.onready(function () {
                    soundManager.createSound({
                        id: 'halloween',
                        url: rootPath + 'Content/sounds/TheDarkeningGround.mp3',
                        autoLoad: true,
                        autoPlay: true,
                        stream: true,
                        volume: 75
                    });
                });
                Setup(rootPath + 'Content/sounds/typewriter.mp3');
                StopButton('halloween');
            </text>
        }
        else if (DateTime.Now.Month == (int)Month.December)
        {
            <text>
                soundManager.onready(function () {
                    soundManager.createSound({
                        id: 'xmas',
                        url: rootPath + 'Content/sounds/Maenam.mp3',
                        autoLoad: true,
                        autoPlay: true,
                        stream: true,
                        volume: 75
                    });
                });
                Setup(rootPath + 'Content/sounds/techtyping.mp3');
                StopButton('xmas');
                $(document).snowfall({ flakeIndex: 9000, minSize: 1, maxSize: 5, round: true, flakeCount: 100 });
            </text>
        }
        else
        {
            @:Setup(rootPath + 'Content/sounds/techtyping.mp3');
        }
    });

    function StopButton(soundName) {
        $('<button><i class="icon-stop"></i></button>')
        .addClass('btn')
        .css({
            position: 'fixed',
            right: 20,
            top: 20,
            cursor: 'pointer',
            zIndex: 9000,
            opacity: '.50'
        })
        .prependTo('body')
        .click(function (e) {
            soundManager.pause(soundName);
            $(this).hide();
            PlayButton(soundName);
        });
    }

    function PlayButton(soundName) {
        $('<button><i class="icon-play"></i></button>')
        .addClass('btn')
        .css({
            position: 'fixed',
            right: 20,
            top: 20,
            cursor: 'pointer',
            zIndex: 9000,
            opacity: '.50'
        }).prependTo('body')
        .click(function (e) {
            soundManager.resume(soundName);
            $(this).hide();
            StopButton(soundName);
        });
    }

    function Setup(soundFile) {
        $.coolType.setup({
            soundFile: soundFile,
            playSound: true,
            speed: 25,
            onSoundLoaded: function () {
                $('#commandForm').terminalClient(
                {
                    elementToScroll: document,
                    apiUrl: '@Url.Action("Index", "Api")',
                    loggedinCallback: function (username) {
                        $(document).trigger('userLoggedIn');
                    },
                    loggedoutCallback: function () {
                        $(document).trigger('userLoggedOut');
                    }
                });
            }
        });
    }
</script>
<img class="backgroundImage" src="@Url.Content("~/content/omega.jpg")">
<div id="frame">
    <div id="terminal">
        @using (Html.BeginForm("Index", "Terminal", FormMethod.Post, new { id = "commandForm" }))
        {
            <div>
                @Html.Serialize("CommandContext", Model.CommandContext)
                <div id="terminalDisplay">
                    <noscript>
                        @Html.Raw(Model.Display)
                    </noscript>
                </div>
                @Html.HiddenFor(x => x.Display)
                <div id="notifications">
                    <noscript>
                        @Html.Raw(Model.Notifications)
                    </noscript>
                </div>
                @Html.HiddenFor(x => x.Notifications)
                <div id="loading">
                </div>
                <span id="contextDisplay"><span id="context">
                    <noscript>@Model.ContextText</noscript>
                </span>&gt;&nbsp;</span>
                @if (Model.PasswordField)
                {
                    @Html.PasswordFor(x => x.Cli, new { autofocus = "autofocus", autocomplete = "off" })
                }
                else
                {
                    @Html.TextBoxFor(x => x.Cli, new { autofocus = "autofocus", autocomplete = "off" })
                }
            </div>
        }
    </div>
</div>